version: '1.0'

services:

  project_food:
    build: project_food/.
    container_name: project-food
    ports:
      - '8000:8000'
    restart: unless-stopped

  telegram:
    build: telegram/.
    container_name: telegram-app
    ports:
      - '4000:4000'
    restart: unless-stopped
    environment:
#      - telegram/configs/.env
#      - todo del

      - 'BOT_USERNAME=@recipe_recommender_bot'
      - 'FAST_API_RECOMMENDER_URL=http://project_food:8000'
      - 'FAST_API_TELEGRAM_URL=http://telegram:4000'
